const interopDefault = r => r.default || r || []
export default {
  "pages/qrquiz/index.vue": () => import('./_nuxt/index-styles.2faea5fa.mjs').then(interopDefault),
  "node_modules/@nuxt/ui-templates/dist/templates/error-500.vue": () => import('./_nuxt/error-500-styles.6b5b5ff2.mjs').then(interopDefault),
  "node_modules/@nuxt/ui-templates/dist/templates/error-404.vue": () => import('./_nuxt/error-404-styles.a5c3f351.mjs').then(interopDefault),
  "components/Qrquiz/User/index.vue": () => import('./_nuxt/index-styles.2dfe0aae.mjs').then(interopDefault),
  "components/Qrquiz/Game/index.vue": () => import('./_nuxt/index-styles.b953f0ca.mjs').then(interopDefault),
  "components/Qrquiz/Result/index.vue": () => import('./_nuxt/index-styles.fe3d7bbb.mjs').then(interopDefault),
  "components/Loading/index.vue": () => import('./_nuxt/index-styles.dc9e088b.mjs').then(interopDefault),
  "components/Qrquiz/NormalQuiz/index.vue": () => import('./_nuxt/index-styles.b20cb6ad.mjs').then(interopDefault),
  "components/Qrquiz/BossQuiz/index.vue": () => import('./_nuxt/index-styles.66effdba.mjs').then(interopDefault),
  "components/Qrquiz/GameMain/index.vue": () => import('./_nuxt/index-styles.29bf4dd7.mjs').then(interopDefault),
  "components/Qrquiz/QuizContents/quiz1.vue": () => import('./_nuxt/quiz1-styles.5a94cec7.mjs').then(interopDefault),
  "components/Qrquiz/QuizContents/quiz2.vue": () => import('./_nuxt/quiz2-styles.2b173349.mjs').then(interopDefault),
  "components/Qrquiz/QuizContents/quiz3.vue": () => import('./_nuxt/quiz3-styles.5fc66066.mjs').then(interopDefault),
  "components/Qrquiz/QuizContents/quiz5.vue": () => import('./_nuxt/quiz5-styles.9bbc7db7.mjs').then(interopDefault),
  "components/Qrquiz/QuizContents/quiz4.vue": () => import('./_nuxt/quiz4-styles.7cd004ec.mjs').then(interopDefault),
  "components/Qrquiz/QuizContents/quiz6.vue": () => import('./_nuxt/quiz6-styles.ef32db4a.mjs').then(interopDefault),
  "components/Qrquiz/QuizTypes/input.vue": () => import('./_nuxt/input-styles.1f9017ab.mjs').then(interopDefault),
  "components/Qrquiz/QuizTypes/numbers.vue": () => import('./_nuxt/numbers-styles.865df9b5.mjs').then(interopDefault),
  "components/Qrquiz/QuizTypes/directions.vue": () => import('./_nuxt/directions-styles.ee0a806f.mjs').then(interopDefault),
  "components/Qrquiz/QuizTypes/choice.vue": () => import('./_nuxt/choice-styles.304d518d.mjs').then(interopDefault),
  "components/Qrquiz/QuizTypes/ox.vue": () => import('./_nuxt/ox-styles.ae367d2b.mjs').then(interopDefault),
  "components/Qrquiz/Modals/index.vue": () => import('./_nuxt/index-styles.fca73dcc.mjs').then(interopDefault),
  "components/Qrquiz/Modals/Help1.vue": () => import('./_nuxt/Help1-styles.138a1a30.mjs').then(interopDefault),
  "components/Qrquiz/Modals/Help2.vue": () => import('./_nuxt/Help2-styles.cc6634f3.mjs').then(interopDefault),
  "components/Qrquiz/Modals/Help3.vue": () => import('./_nuxt/Help3-styles.e1358345.mjs').then(interopDefault)
}